name: fintech_payments
version: "1.0.0"
config-version: 2

profile: fintech_payments

model-paths:
  - models
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots

target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  fintech_payments:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
