"""Role-aware Portal configuration contracts."""

from portal_api.configuration.errors import (
    ConfigurationDiagnostic,
    PortalConfigurationError,
    PortalConfigurationWarning,
)
from portal_api.configuration.inventory import (
    PORTAL_API_PREFIX,
    PORTAL_API_SECRET_FIELDS,
    environment_alias,
    supported_environment_aliases,
    unknown_prefixed_environment_names,
)
from portal_api.configuration.migration import MigrationEnvironmentInputs
from portal_api.configuration.models import (
    AbuseConfiguration,
    ApiRuntimeConfiguration,
    AuditConfiguration,
    AuditWorkerRuntimeConfiguration,
    EnvironmentSecretInputs,
    HealthConfiguration,
    HttpServerConfiguration,
    KeyRotationConfiguration,
    LoggingConfiguration,
    LoginPolicyConfiguration,
    MigrationRuntimeConfiguration,
    OidcConfiguration,
    PortalProcessRole,
    PortalRoleConfiguration,
    ProviderLifecycleConfiguration,
    ReleaseConfiguration,
    SecretReferenceConfiguration,
    SecurityRuntimeConfiguration,
    SessionPolicyConfiguration,
    TelemetryConfiguration,
)

__all__ = [
    "PORTAL_API_PREFIX",
    "PORTAL_API_SECRET_FIELDS",
    "AbuseConfiguration",
    "ApiRuntimeConfiguration",
    "AuditConfiguration",
    "AuditWorkerRuntimeConfiguration",
    "ConfigurationDiagnostic",
    "EnvironmentSecretInputs",
    "HealthConfiguration",
    "HttpServerConfiguration",
    "KeyRotationConfiguration",
    "LoggingConfiguration",
    "LoginPolicyConfiguration",
    "MigrationEnvironmentInputs",
    "MigrationRuntimeConfiguration",
    "OidcConfiguration",
    "PortalConfigurationError",
    "PortalConfigurationWarning",
    "PortalProcessRole",
    "PortalRoleConfiguration",
    "ProviderLifecycleConfiguration",
    "ReleaseConfiguration",
    "SecretReferenceConfiguration",
    "SecurityRuntimeConfiguration",
    "SessionPolicyConfiguration",
    "TelemetryConfiguration",
    "environment_alias",
    "supported_environment_aliases",
    "unknown_prefixed_environment_names",
]
